# Use an official Python runtime as a parent image for building
FROM python:3.12-slim AS builder

# Set this environment variable to suppress the "Running as root" warning from pip
ENV PIP_ROOT_USER_ACTION=ignore

# Set the working directory in the container to /app
WORKDIR /app

# Install necessary packages for building Python packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc libc-dev python3-dev libffi-dev build-essential && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy requirements and project files needed for installation
COPY requirements.txt .
COPY pyproject.toml ./
COPY rosemary/ ./rosemary

# Update pip and install Python packages
RUN pip install --upgrade pip --no-cache-dir
RUN pip install -r requirements.txt

# Install Rosemary
RUN pip install -e ./


# Use an official Python runtime as a parent image for runtime
FROM python:3.12-slim

# Set this environment variable to suppress the "Running as root" warning from pip
ENV PIP_ROOT_USER_ACTION=ignore

# Set the working directory in the container to /app
WORKDIR /app

# Install runtime dependencies only
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    mariadb-client curl bash openrc ca-certificates gnupg lsb-release && \
    # Install Docker CLI
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends docker-ce-cli && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy Python packages from the builder stage
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy scripts and set execution permissions
COPY --chmod=0755 scripts/wait-for-db.sh ./scripts/
COPY --chmod=0755 scripts/init-testing-db.sh ./scripts/

# Copy the project files
COPY rosemary/ ./rosemary
COPY docker/ ./docker

# Expose port 5000 for the Flask app
EXPOSE 5000