"""002

Revision ID: 002
Revises: 001
Create Date: 2025-11-06 17:50:22.833897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solver', sa.Text(), nullable=True),
    sa.Column('not_solver', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('md_meta_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mmd_filename', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('diagram_type', sa.Enum(
        'FLOWCHART',
        'SEQUENCE_DIAGRAM',
        'CLASS_DIAGRAM',
        'STATE_DIAGRAM',
        'ENTITY_RELATIONSHIP_DIAGRAM',
        'USER_JOURNEY',
        'GANTT',
        'PIE_CHART',
        'QUADRANT_CHART',
        'REQUIREMENT_DIAGRAM',
        'GITGRAPH_DIAGRAM',
        'C4_DIAGRAM',
        'MINDMAPS',
        'TIMELINE',
        'ZENUML',
        'SANKEY',
        'XYCHART',
        'BLOCKDIAGRAM',
        'PACKET',
        'KANBAN',
        'ARCHITECTURE',
        'RADAR',
        'TREEMAP',
        name='diagramtype'
    ), nullable=False),
    sa.Column('publication_doi', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.String(length=120), nullable=True),
    sa.Column('mmd_version', sa.String(length=120), nullable=True),
    sa.Column('md_metrics_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['md_metrics_id'], ['md_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mermaid_diagram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_set_id', sa.Integer(), nullable=False),
    sa.Column('md_meta_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['md_meta_data_id'], ['md_meta_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

# ### INICIO DEL CÓDIGO PARA ds_meta_data (Versión MAYÚSCULAS) ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        
        # --- PASO 1: Mapear datos antiguos ---
        # Convierte todos los valores antiguos a 'FLOWCHART' por defecto.
        old_publication_types_list = [
            'NONE', 'ANNOTATION_COLLECTION', 'BOOK', 'BOOK_SECTION', 'CONFERENCE_PAPER',
            'DATA_MANAGEMENT_PLAN', 'JOURNAL_ARTICLE', 'PATENT', 'PREPRINT',
            'PROJECT_DELIVERABLE', 'PROJECT_MILESTONE', 'PROPOSAL', 'REPORT',
            'SOFTWARE_DOCUMENTATION', 'TAXONOMIC_TREATMENT', 'TECHNICAL_NOTE',
            'THESIS', 'WORKING_PAPER', 'OTHER'
        ]
        old_values_sql_in = ", ".join([f"'{val}'" for val in old_publication_types_list])
        
        # Mapeamos al nuevo valor por defecto en MAYÚSCULAS
        batch_op.execute(
            f"UPDATE ds_meta_data SET publication_type = 'FLOWCHART' "
            f"WHERE publication_type IN ({old_values_sql_in})"
        )

        # --- PASO 2: Alterar la columna ---
        # Renombra 'publication_type' a 'diagram_type' y cambia el ENUM
        new_diagram_types_list_uppercase = [
            'FLOWCHART', 'SEQUENCE_DIAGRAM', 'CLASS_DIAGRAM', 'STATE_DIAGRAM',
            'ENTITY_RELATIONSHIP_DIAGRAM', 'USER_JOURNEY', 'GANTT', 'PIE_CHART',
            'QUADRANT_CHART', 'REQUIREMENT_DIAGRAM', 'GITGRAPH_DIAGRAM', 'C4_DIAGRAM',
            'MINDMAPS', 'TIMELINE', 'ZENUML', 'SANKEY', 'XYCHART', 'BLOCKDIAGRAM',
            'PACKET', 'KANBAN', 'ARCHITECTURE', 'RADAR', 'TREEMAP'
        ]
        
        batch_op.alter_column(
            'publication_type',
            new_column_name='diagram_type',
            # Usamos la nueva lista en MAYÚSCULAS
            type_=sa.Enum(*new_diagram_types_list_uppercase, name='diagramtype'),
            existing_type=mysql.ENUM(*old_publication_types_list, name='publicationtype'),
            existing_nullable=False
        )
    # ### FIN DEL CÓDIGO PARA ds_meta_data ###

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('md_meta_data_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('author_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'md_meta_data', ['md_meta_data_id'], ['id'])
        batch_op.drop_column('fm_meta_data_id')

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_diagrams', sa.String(length=120), nullable=True))
        batch_op.drop_column('number_of_models')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mermaid_diagram_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('file_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'mermaid_diagram', ['mermaid_diagram_id'], ['id'])
        batch_op.drop_column('feature_model_id')
    op.drop_table('webhook')
    op.drop_table('feature_model')
    op.drop_table('fm_meta_data')
    op.drop_table('fm_metrics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('file_ibfk_1'), 'feature_model', ['feature_model_id'], ['id'])
        batch_op.drop_column('mermaid_diagram_id')

    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_models', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('number_of_diagrams')

    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('author_ibfk_2'), 'fm_meta_data', ['fm_meta_data_id'], ['id'])
        batch_op.drop_column('md_meta_data_id')

    op.create_table('feature_model',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data_set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fm_meta_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], name=op.f('feature_model_ibfk_1')),
    sa.ForeignKeyConstraint(['fm_meta_data_id'], ['fm_meta_data.id'], name=op.f('feature_model_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fm_meta_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uvl_filename', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('diagram_type', mysql.ENUM(), nullable=False),
    sa.Column('publication_doi', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('uvl_version', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fm_metrics_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fm_metrics_id'], ['fm_metrics.id'], name=op.f('fm_meta_data_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fm_metrics',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('solver', mysql.TEXT(), nullable=True),
    sa.Column('not_solver', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('webhook',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('mermaid_diagram')
    op.drop_table('md_meta_data')
    op.drop_table('md_metrics')
    # ### end Alembic commands ###
