"""Add is_draft column

Revision ID: 692fd14c9a69
Revises: 0d36f42ec39f
Create Date: 2025-12-10 20:08:14.181258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692fd14c9a69'
down_revision = '0d36f42ec39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.drop_column('is_draft')

    # ### end Alembic commands ###
